#
#                  ⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀  ⣿⣿⣿⣿
#                  ⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀  ⣿⣿⣿⣿
#                  ⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀  ⣿⣿⣿⣿
#                  ⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀   ⣀⣿⣿⣿⣿
#  ███╗   ██╗██████╗⠛⠿⣿⣿⣿⣶⣤██╗⣀⣀⣀ ██╗████████╗██╗      ██╗ ██╗     ██╗
#  ████╗  ██║██╔══██╗  ⠉⠛⠿⣿██║⣤⣀⣤⣶██║██╔═════╝██║      ██║ ╚═██╗ ██╔═╝
#  ██╔██╗ ██║██║  ██║█████╗█████████║████████╗██║      ██║   ╚═██╔═╝
#  ██║╚██╗██║██║  ██║╚════╝██║⠛⠉⠛⠿██║██╔═════╝██║      ██║   ██╔═██
#  ██║ ╚████║██████╔╝⣤⣶⣿⣿⣿⠿██║⠉⠉⠉⠛██║████████╗████████╗██║ ██╔═╝ ╚═██╗
#  ╚═╝  ╚═══╝╚═════╝⣿⣿⣿⠉   ╚═╝⠉⠉⠛⠛╚═╝╚═══════╝╚═══════╝╚═╝ ╚═╝     ╚═╝
#                  ⣿⣿⣿⣿   ⠉⠉⠉⠉⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⣿⣿⣿⣿
#                  ⣿⣿⣿⣿   ⠉⠉⠉⠉⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⣿⣿⣿⣿
#                  ⣿⣿⣿⣿   ⠉⠉⠉⠉⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⣿⣿⣿⣿
#
# ========== General ========== #
theme = "ayu_dark"
# good themes: [ ayu_dark, bogster, fleet_dark, onedark, onedarker, tokyonight, dracula ]


# ========== Editor ========== #
[editor]
line-number = "relative"
mouse = true
color-modes = true
cursorline = true
shell = ["zsh"]
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["selections", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = false
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true
auto-signature-help	= true
display-signature-help-docs	= true

# Auto-pairs
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

# ========== Keybinds ========== #
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"backspace" = { s = [":w", ":config-reload"]}
"$" = "goto_line_end"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
0 = "goto_line_start"
V = ["select_mode", "extend_to_line_bounds"]
G = "goto_file_end"
x = ["yank_main_selection_to_clipboard", "delete_selection"]
t = ["select_mode", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
s = ":sort"

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.normal.c]
i = { w = ["select_mode", "move_next_word_start", "delete_selection", "collapse_selection", "insert_mode"]}
c = "toggle_comments"
a = "code_action"

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.space]
"space" = { w = [":w"]}
"f" = "file_picker"

[keys.normal.space.x]
"u" = "switch_to_lowercase"
"U" = "switch_to_uppercase"

[keys.normal.space.g]
"$" = "goto_line_end"
"0" = "goto_line_start"
"d" = "goto_definition"
"g" = "goto_file_start"
"G" = "goto_file_end"
"h" = "goto_line_start"
"i" = "goto_implementation"
"l" = "goto_line_end"
"m" = "goto_last_modification"
"t" = "goto_window_top"
"b" = "goto_window_bottom"
"c" = "goto_window_center"
"r" = "goto_reference"
"s" = "symbol_picker"
"S" = "workspace_symbol_picker"
"w" = "goto_first_nonwhitespace"
"y" = "goto_type_definition"

[keys.normal.space.c]
"c" = "switch_case"

[keys.normal.space.b]
"b" = "buffer_picker"
"d" = ":buffer-close"
"D" = ":buffer-close!"
"n" = "goto_next_buffer"
"p" = "goto_previous_buffer"
"r" = ":reload"
"s" = ":new"
"y" = ["select_all", ":clipboard-yank"]
"Y" = ["select_all", "yank"]

[keys.normal.space.e]
"l" = "workspace_diagnostics_picker"
"n" = "goto_next_diag"
"p" = "goto_prev_diag"
"g" = "goto_first_diag"
"G" = "goto_last_diag"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"%" = "match_brackets"
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
i = "select_textobject_inner"
y = { y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]}
d = ["yank_main_selection_to_clipboard", "delete_selection"]
a = "select_textobject_around"
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
P = "paste_clipboard_before"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
u = ["switch_to_lowercase", "collapse_selection"]
U = ["switch_to_uppercase", "collapse_selection"]